package net.spartanb312.bipbap.gradle.android

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

abstract class BipbapAndroidProguardRulesTask : DefaultTask() {

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "bipbap"
        description = "Generates ProGuard/R8 keep rules for Bipbap Android output."
    }

    @TaskAction
    fun generate() {
        val file = outputFile.get().asFile
        file.parentFile.mkdirs()
        file.writeText(RULES)
        logger.quiet("[Bipbap] Generated ProGuard/R8 keep rules: ${file.absolutePath}")
    }

    companion object {
        private val RULES = """
            # Generated by the Bipbap Android Gradle Plugin.
            # Bipbap runs before R8/ProGuard; keep generated constant containers intact.
            -keep class **${'$'}Constants { *; }

        """.trimIndent()
    }
}
